### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by o**

### CODE REVIEW

**Comment by lacivert** [comment]
:thumbsup:

**Comment by emre** [comment]
I don't think that's a good idea since the whole project encourages .DS_Store files  in directories. I am marking this as "design decision needed". I am not sure what to do at the moment.

@martey

what do you think about this?

**Comment by o** [comment]
Hey @martey, how about this feature?

**Comment by martey** [comment]
I think it would need an exception in order not to ignore the .DS_Store file already included in the project.

**Comment by bjorn** [comment]
Luckily `.gitignore` doesn't cause files that are already tracked by git to be ignored.

**Pull request merged**
